name: Build

on:
  push:
  pull_request_target:
    types: [labeled]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.1'
          distribution: 'graalvm' # See 'Options' for all available distributions
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Test
        run: >
          mvn -B clean verify
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: hub-cli-reports
          path: |
            target/dependency-check-report.html
            target/surefire-reports/*
          if-no-files-found: error
      - name: Draft a release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          generate_release_notes: true
          body: |-
            :construction: Work in Progress
            
            ⏳ Please be patient, the builds are still [running](https://github.com/cryptomator/hub-cli/actions). New versions of hub-cli can be found here in a few moments. ⏳
            
            ---
            <!-- Don't forget to include the 💾 SHA-256 checksums of release artifacts: -->