name: Build native image

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  build:
    name: Build a native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.1'
          distribution: 'graalvm'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build develop native image
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: >
          mvn -B clean package -Pnative
      - name: Build release native image
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          mvn -B clean package -Pnative,release
      - name: Create detached GPG signatures
        run: |
          gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 615D449FE6E6A235 --detach-sign -a target/hub
          gpg --batch --quiet --passphrase-fd 0 --pinentry-mode loopback -u 615D449FE6E6A235 --detach-sign -a target/HubCli_completion.sh
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: hub-cli
          path: |
            target/hub
            target/HubCli_completion.sh
            hub.asc
            HubCli_completion*.asc
          if-no-files-found: error
      - name: Publish executable on Github Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          token: ${{ secrets.CRYPTOBOT_RELEASE_TOKEN }}
          files: |
            target/hub
            target/HubCli_completion.sh
            hub.asc
            HubCli_completion*.asc
